- name: Copy Elastic Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx
    
- name: Copy nginx Config
  ansible.builtin.template:
    src: http_proxy.conf
    dest: /etc/nginx/nginx.conf

- name: Copy LogStash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start and enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

