- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: present

- name: Install PyMySQL for Python 2.7
  ansible.builtin.pip:
    name: PyMySQL
    state: present

- name: Change root password
  ansible.builtin.mysql_user:
    name: root
    password: RoboShop@1
    host: mysql-dev.devopsprojects.store
    state: present
  become: yes
  become_method: sudo


- name: Load Schema
  ansible.builtin.command:
    cmd: mysql -h mysql-dev.devopsprojects.store -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql

